formatter: "markdown document" # this is required

version: "0.16.0"

header-from: docs/header.md
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |
  {{ .Header }}
  
  ## Usage
  
  Minimal
  ```hcl
  {{ include "docs/examples/minimal.tf" }}
  ```
  
  Full example
  ```hcl
  {{ include "docs/examples/full.tf" }}
  ```
  
  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Providers }}
  
  {{ .Resources }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
